# Generated by Django 4.0.4 on 2022-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_email', models.EmailField(max_length=30)),
                ('teacher_password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'teacher_reg',
            },
        ),
    ]
