# Generated by Django 4.0.4 on 2024-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_title', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Application Name',
            },
        ),
    ]
