# Generated by Django 4.0.4 on 2024-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationname',
            name='logo_of_project',
            field=models.ImageField(default='images/default.jpg', upload_to='images/logo'),
        ),
    ]
