# Generated by Django 4.0.4 on 2022-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220610_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_picture',
            field=models.ImageField(upload_to='admissionDocuments/'),
        ),
        migrations.AlterField(
            model_name='teacher_reg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
