# Generated by Django 4.0.4 on 2022-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentmodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Student_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('semester', models.CharField(max_length=200, null=True)),
                ('program', models.CharField(max_length=200, null=True)),
                ('period', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Absent', max_length=200, null=True)),
            ],
        ),
    ]
