# Generated by Django 4.0.4 on 2024-01-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='custom_unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
