# Generated by Django 4.0.4 on 2024-01-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
