# Generated by Django 4.0.4 on 2024-01-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_attendance_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='application_type',
        ),
    ]
