# Generated by Django 4.0.4 on 2024-01-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_remove_appuser_image_path_appuser_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
