# Generated by Django 4.0.4 on 2024-01-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_appuser_custom_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
